from tkinter import * 
window = Tk()
window.title("number pad")
window.geometry("350x350")
frame = Frame(window, height = 100, width = 100, bg = "light blue")
frame.place(x = 175, y = 175, anchor= "center")
num1 = Label(frame, text= "1", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num1.grid(row= 0, column = 0, pady= 20, padx= 20)
num2 = Label(frame, text= "2", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num2.grid(row= 0, column = 1, pady= 20, padx= 20)
num3 = Label(frame, text= "3", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num3.grid(row= 0, column = 2, pady= 20, padx= 20)
num4 = Label(frame, text= "4", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num4.grid(row= 1, column = 0, pady= 20, padx= 20)
num5 = Label(frame, text= "5", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num5.grid(row= 1, column = 1, pady= 20, padx= 20)
num6 = Label(frame, text= "6", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num6.grid(row= 1, column = 2, pady= 20, padx= 20)
num7 = Label(frame, text= "7", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num7.grid(row= 2, column = 0, pady= 20, padx= 20)
num8 = Label(frame, text= "8", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num8.grid(row= 2, column = 1, pady= 20, padx= 20)
num9 = Label(frame, text= "9", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num9.grid(row= 2, column = 2, pady= 20, padx= 20)
numstar = Label(frame, text= "*", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
numstar.grid(row= 3, column = 0, pady= 20, padx= 20)
num0 = Label(frame, text= "0", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
num0.grid(row= 3, column = 1, pady= 20, padx= 20)
numhash = Label(frame, text= "#", bg= "yellow", font= ("Arial", 25, "bold"), width= 2)
numhash.grid(row= 3, column = 2, pady= 20, padx= 20)
window.mainloop()